 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://172.22.17.117:5001
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 582-330-351
Traceback (most recent call last):
  File "/Users/pihu/Desktop/project_folder/app.py", line 57, in <module>
    socketio.run(app, debug=True, host='0.0.0.0', port=5001)  # Change port
  File "/Users/pihu/Library/Python/3.9/lib/python/site-packages/flask_socketio/__init__.py", line 660, in run
    app.run(host=host, port=port, threaded=True,
  File "/Users/pihu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 662, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/pihu/Library/Python/3.9/lib/python/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
  File "/Users/pihu/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
  File "/Users/pihu/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
